# Ex3 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [ ]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|', index_col='user_id')

### Step 4. See the first 25 entries

In [ ]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [ ]:
users.tail(10)

### Step 6. What is the number of observations in the dataset?

In [ ]:
users.shape[0]

### Step 7. What is the number of columns in the dataset?

In [ ]:
users.shape[1]

### Step 8. Print the name of all the columns.

In [ ]:
users.columns

### Step 9. How is the dataset indexed?

In [ ]:
users.index

### Step 10. What is the data type of each column?

In [ ]:
users.dtypes

### Step 11. Print only the occupation column

In [ ]:
users['occupation']

### Step 12. How many different occupations are in this dataset?

In [ ]:
users['occupation'].value_counts().shape[0]

### Step 13. What is the most frequent occupation?

In [ ]:
users['occupation'].value_counts().head(1)

### Step 14. Summarize the DataFrame.

In [ ]:
users.describe()

### Step 15. Summarize all the columns

In [ ]:
users.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [ ]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

(round to a whole number(make it integer))

In [ ]:
round(users['age'].mean())

34

### Step 18. What is the age with least occurrence?

In [ ]:
users['age'].value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64